Add SPI Methods trait and vtable
ks0n/linux pull request #8
Opened 2021-05-19 08:22 UTC by CohenArthur

This will need a few refactorings, but I'd like to get the first basic implementation reviewed. This is super similar to what's being done in `FileOperations` and would probably deserve some code factoring (for example, a general macro to declare "vtables" and their usage in a generic trait.

I also wonder if this part
```rust
         match T::TO_USE.probe {
            false => spi_driver.probe = None,
            true => spi_driver.probe = Some(DriverRegistration::probe_wrapper::<T>),
        }
        match T::TO_USE.remove {
            false => spi_driver.remove = None,
            true => spi_driver.remove = Some(DriverRegistration::remove_wrapper::<T>),
        }
        match T::TO_USE.shutdown {
            false => spi_driver.shutdown = None,
            true => spi_driver.shutdown = Some(DriverRegistration::shutdown_wrapper::<T>),
        }
```
would benefit from some sort of macro or private function? Since it's very repetitive code, we could do something like
```rust
fn get_wrapper<F>(usage: bool, fn: F) -> Option<F> {
    match usage {
        false => None,
        true => Some(F),
    }
}
```

Please let me know what you guys think :)

2021-05-19 16:27 UTC, n1tram1 approved these changes

2021-05-19 21:43 UTC, Skallwar requested changes

2021-05-19 21:43 UTC, Skallwar commented on rust/kernel/spi.rs
> +}
Can you provide an example of how to use this?

2021-05-19 21:45 UTC, Skallwar commented on rust/kernel/spi.rs
> +}
And how it works :sweat_smile:

2021-05-19 22:02 UTC, Skallwar commented
``get_wrapper`` refactor is a good idea

2021-05-20 20:12 UTC, Skallwar approved these changes

2021-05-20 20:18 UTC, merged